--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Katsu-MC/ShulkerDye
build-by-default: true
branches:
- main
projects:
  ShulkerDye:
    path: ""
    lint: false
    icon: icon.png
...
